Change to sdk-project file format
Flexberry/NewPlatform.Flexberry.ORM.ODataService pull request #167
Opened 2020-10-15 11:57 UTC by bratchikov

2020-10-22 17:32 UTC, NicholasNoise commented on Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/BaseODataServiceIntegratedTest.cs
> +                HttpClient client = _factory.CreateClient();
Получается, что контейнер никак не связан с фабрикой и сервером.

2020-10-29 15:39 UTC, NicholasNoise requested changes

2020-10-29 15:39 UTC, NicholasNoise commented on Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/BaseIntegratedTest.cs
> +#if NETCORE
В sdk-формате предопределены константы: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives/preprocessor-if

Замени `NETCORE` на `NETCOREAPP`

2020-10-29 15:39 UTC, NicholasNoise commented on Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/DotNetCoreTests.cs
> +﻿#if NETCORE
Лучше специфичные для фреймворка файлы исключать через csproj:
```
  <ItemGroup Condition="!$(DefineConstants.Contains(NETCOREAPP))">
    <Compile Remove="DotNetCoreTests.cs" />
  </ItemGroup>
```

2020-10-29 15:39 UTC, NicholasNoise commented on Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/ExceptionMiddleware.cs
> +    public class ExceptionMiddleware
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-3.1#exception-handler-lambda-1
А так не проще?

2020-10-29 15:39 UTC, NicholasNoise commented on Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/NewPlatform.Flexberry.ORM.ODataService.Tests.csproj
> +	<PackageReference Include="Microsoft.AspNetCore" Version="2.2.0" />
Выравнивание

2020-10-29 15:39 UTC, NicholasNoise commented on Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/NewPlatform.Flexberry.ORM.ODataService.Tests.csproj
> +    <PackageReference Include="System.Text.Encoding.CodePages" Version="4.5.1" />
Порядок

2020-10-29 18:28 UTC, bratchikov commented on Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/BaseIntegratedTest.cs
> +#if NETCORE
Готово

2020-10-29 18:31 UTC, bratchikov commented on Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/DotNetCoreTests.cs
> +﻿#if NETCORE
Такая настройка в csproj - не самый явный вариант. Непосвящённый программист будет долго соображать почему этот файл не компилируется. Может быть потом придём к предлагаемому твобой варианту как основному, вынесем всю двойную логику в разные файлы.

2020-10-29 18:42 UTC, bratchikov commented on Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/ExceptionMiddleware.cs
> +    public class ExceptionMiddleware
Не знаю, я нагуглил такое вот решение для 2.2 и интеграционных тестов. Переделывать уже не хочется, поскольку с задачей этот обработчик справляется - исключения преобразует в код ответа и брекпоинт поставить можно.

2020-10-29 18:51 UTC, bratchikov commented on Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/NewPlatform.Flexberry.ORM.ODataService.Tests.csproj
> +	<PackageReference Include="Microsoft.AspNetCore" Version="2.2.0" />
Исправлено

2020-10-29 18:51 UTC, bratchikov commented on Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/NewPlatform.Flexberry.ORM.ODataService.Tests.csproj
> +    <PackageReference Include="System.Text.Encoding.CodePages" Version="4.5.1" />
Исправлено

2020-10-29 19:16 UTC, NicholasNoise commented on Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/DotNetCoreTests.cs
> +﻿#if NETCORE
Слабый духом разработчик от условной компиляции может сойти с ума, но это совсем другая история

2020-10-29 19:19 UTC, NicholasNoise commented on Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/DotNetCoreTests.cs
> +﻿#if NETCORE
Исключение через файл проекта лучше показывает, какого функционала нет для определенного фреймворка - весь перечень в одном месте

2020-10-29 19:21 UTC, NicholasNoise approved these changes

2020-10-29 19:21 UTC, NicholasNoise commented on Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/NewPlatform.Flexberry.ORM.ODataService.Tests.csproj
> +  <PropertyGroup Condition=" '$(TargetFramework)' == 'net461' ">
Удалить оба переопределения `DefineConstants` - уже встроено в `Microsoft.NET.Sdk`, ссылка выше

2020-10-30 02:20 UTC, merged