Change load data for excel export
Flexberry/NewPlatform.Flexberry.ORM.ODataService pull request #214
Opened 2021-01-20 12:33 UTC by AntonIV8

2021-01-27 12:38 UTC, bratchikov requested changes

2021-01-27 12:56 UTC, AntonIV8 commented on NewPlatform.Flexberry.ORM.ODataService/Controllers/DataObjectController.cs
> +            foreach (var propType in Information.GetAllTypesFromView(lcs.View))
Ага, проглядел

2021-01-27 12:56 UTC, AntonIV8 commented on NewPlatform.Flexberry.ORM.ODataService/Controllers/DataObjectController.cs
> +                else
Я над этим еще подумаю

2021-10-06 10:26 UTC, bratchikov commented
replaced with #237

2021-10-06 10:26 UTC, closed without merging