checking with identical PublishName
Flexberry/NewPlatform.Flexberry.ORM.ODataService pull request #251
Opened 2022-05-25 06:20 UTC by neroslovegor

2022-05-27 09:14 UTC, bratchikov requested changes

2022-05-27 09:14 UTC, bratchikov commented on NewPlatform.Flexberry.ORM.ODataService/Model/DataObjectEdmModel.cs
> +                    throw new Exception($"Класс с PublishName {edmEntityType.Name} уже добавлен.");
Please use English into exception messages.

2022-05-27 09:14 UTC, bratchikov commented on NewPlatform.Flexberry.ORM.ODataService/Model/DataObjectEdmModel.cs
> +                    throw new Exception($"Класс в PublishName {typeSettings.CollectionName} уже добавлен.");
Please use English into exception messages. 
Хорошим тоном считается написать такое сообщение, по которому пользователю или хотя бы программисту будет понятно что делать в случае возникновения ошибки. В данном случае надо намекнуть на то, что нужно проверить не повторяется ли такой-то PublishName в классах (если можно вывести в каких, то ещё интереснее).

2023-11-10 09:08 UTC, Anisimova2020 commented
Требуется:
1) влить изменения из develop-ветки.
2) добавить информацию в Changelog об изменениях.

2024-02-21 08:51 UTC, closed without merging