Решение проблемы с батч-запросом
Flexberry/NewPlatform.Flexberry.ORM.ODataService pull request #294
Opened 2024-02-14 04:59 UTC by Anisimova2020

На рассмотрении был батч-запрос, где приходила сложная иерархическая структура с наследованиями, детейлами и мастеровыми связями между детейлами. В результате выполнения батч-запроса некорректно перетирались кэши, от чего происходил сбой выполнения.
Исправление более аккуратно производит догрузку мастеров (ранее они могли быть перетёрты), а также при догрузке детейлов совсем не смешивает кэши (что приводило к очень отдалённым последствиям).

2024-02-14 06:30 UTC, s-andrey approved these changes

2024-02-14 08:43 UTC, bratchikov requested changes

2024-02-14 08:43 UTC, bratchikov commented on NewPlatform.Flexberry.ORM.ODataService/Extensions/DataServiceExtensions.cs
> +                        { // Если мастера ранее не было в кэше, то просто его туда переносим.
Проверь, что у тебя линтер работает корректно в VS. Как минимум, свежий код надо форматировать красиво.

2024-02-14 08:43 UTC, bratchikov commented on Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/CRUD/BatchTest.cs
> +            /* Суть теста в том, что сначала в батч-запрос идёт мастер, а далее идёт сам объект со ссылкой на мастера.
Добавь это описание в основной XML-комментарий теста, иначе это выглядит очень странно.

2024-02-14 09:13 UTC, Anisimova2020 commented on NewPlatform.Flexberry.ORM.ODataService/Extensions/DataServiceExtensions.cs
> +                        { // Если мастера ранее не было в кэше, то просто его туда переносим.
Поправила.

2024-02-14 09:33 UTC, bratchikov approved these changes

2024-02-14 11:35 UTC, merged

2024-02-20 04:34 UTC, mao29 commented on Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/CRUD/BatchTest.cs
> +                Assert.NotNull(poroda1);
А почему Assert-ы внутри секции Arrange?

2024-02-20 04:34 UTC, mao29 commented on NewPlatform.Flexberry.ORM.ODataService/Controllers/DataObjectController.ModifyData.cs
> +                            _dataService.SafeLoadWithMasters(miniView, dataObjectFromCache, DataObjectCache);
А это не должно быть дефолтным поведением LoadObject-а? Если я в прикладном коде захочу подобный граф объектов загрузить я с такой же проблемой перетирания измененных полей объектов в кеше столкнусь?

2024-02-21 07:46 UTC, Anisimova2020 commented on NewPlatform.Flexberry.ORM.ODataService/Extensions/DataServiceExtensions.cs
> +            if (!loadedObjectsAdded)
Это мини-оптимизация. До вызова этого метода уже проверки проходили. Чтобы не лезть повторно в кэш попусту, сделано так.

2024-02-21 07:48 UTC, Anisimova2020 commented on NewPlatform.Flexberry.ORM.ODataService/Extensions/DataServiceExtensions.cs
> +        /// <param name="loadedObjectsAdded">Флаг, определяющий, что в кэш уже добавлен свежезагруженный объект.</param>
Этот параметр акцентирует на этом внимание.
Ещё несколько мест сомнительных есть, там этот флаг понадобится, поэтому пока оставила.

2024-02-21 07:51 UTC, Anisimova2020 commented on Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/CRUD/BatchTest.cs
> +                Assert.NotNull(poroda1);
Мне показалось, что это наиболее разумный способ проверить, что тестовая среда создалась корректно. Делать такие проверки после Act нелогично.
Как в таком случае разумно поступать?

2024-02-21 08:26 UTC, mao29 commented on NewPlatform.Flexberry.ORM.ODataService/Controllers/DataObjectController.ModifyData.cs
> +                            _dataService.SafeLoadWithMasters(miniView, dataObjectFromCache, DataObjectCache);
Обычно да, но на прикладном уровне и кеш обычно не передают. А вот если передают, то наверное ожидается что объекты в кеше не попортятся

2024-02-21 08:27 UTC, mao29 commented on Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/CRUD/BatchTest.cs
> +                Assert.NotNull(poroda1);
А зачем это проверять? Если создалась некорректно, тест упадет наверное и так, на других проверках

2024-02-21 08:29 UTC, mao29 commented on NewPlatform.Flexberry.ORM.ODataService/Extensions/DataServiceExtensions.cs
> +            if (!loadedObjectsAdded)
Проверяли что она действительно дает значимый прирост скорости? Просто наличие подобного параметра, который к тому же можно некорректно передать (то бишь передать true, а в кеше объекта не будет), мне кажется должно ощутимую выгоду давать